# TP4 : Logiques et Brachistochrone


# Partie I. Brachistochrone


Le Brachistochrone (temps le plus court en grec ancien) est le nom donné à une expérience qui permet de montrer que le chemin le plus rapide n'est pas toujours celui que l'on croît ! Nous avons repris les images d'une expérience réalisée à l'EPFL en Suisse. L'expérience  a été filmée avec une caméra rapide avec 940 images par seconde.


Les boules partent au même moment avec une vitesse initiale nulle. 
Après avoir constaté l'ordre d'arrivée des boules, on souhaite analyser plus en détail cette expérience:

*  Tout d'abord on va étudier le déplacement d'une boule roulant sur un plan incliné tout du long (boule blanche). On va approcher l'expérience par un modèle théorique. 
*  Ensuite, on étudiera chaque trajectoire et on calculera sa longueur. On estimera aussi la vitesse moyenne de chaque boule entre le point de départ et le point d'arrivée. 

Il sera nécessaire d'importer les bibliothèques suivantes : 

In [3]:
import numpy as np
import matplotlib
matplotlib.use('Qt4Agg')
import matplotlib.pyplot as plt


## I.1) Mouvement d'une boule sur un plan incliné. Boule blanche

On ne s'intéresse, dans un premier temps, qu'à la boule blanche qui est placée sur le plan incliné.
En négligeant la contribution des forces de frottement mais en tenant compte de l'inertie de la boule, il est possible de montrer que la distance horizontale parcourue $x(t)$ évolue comme :

$x= A t^2, \quad A = K g \cos (\alpha) \sin (\alpha)$

$g=9.81 m/s^2$ est l’accélération de la gravité, 

$\alpha$ est l’angle entre le plan incliné et l’horizontale, et t est le temps compté depuis le lâcher de la boule 
(l’image initiale).  

Nous allons calculer la valeur de $K$ qui permet d'approcher au mieux les mesures de l'expérience.



1) Lisez l’image *brachistochrone9.png* et affichez-la dans une fenêtre graphique. Cette image de 2160x3840 pixels est constituée de 9 sous images de 720x1280 pixels. Le temps défile en parcourant les images du haut en bas puis de gauche à droite.

2) En utilisant l'outil *ginput*, calculez la taille d’un pixel de l’image en mètres, en prenant pour étalon la largeur de la plaque en bois $L=0.80m$.
 
3) Le vecteur temps: Le film est pris à 940 prises de vue par seconde, mais pour construire l'image nous n'avons retenu que les images 1, 82,  163, 244, 325, 406,  487,   568 et  649.  Construisez le tableau *tvec* qui contient les valeurs successives des temps  de notre expérience (ce tableau a neuf éléments: le nombre de prises de vue selectionnées).

4) On appelle $x(t)$ la distance horizontale de la boule aux temps t successifs.  A l'aide de data cursor, mesurez sur l'image les positions horizontales aux différents instants  (en pixels) de la boule. La position horizontale à $t=0$  de la boule  correspond au point $x=0$. Utiliser la taille d’un pixel calculée à la question 2, et si besoin la taille des sous-images  pour en déduire les 9 valeurs successives de $x(t)$ en mètres. 

5) Tracez le graphique de $x$ (en mètres) en fonction de $t$ (en secondes). Annotez votre graphique : labels, titre. 



In [16]:

## Partie I. 
# Mouvement d'une boule sur un plan incliné
# Parametres du probleme
g=9.81
fps=940 # Nombre d'images par seconde (frame per sec)
larg_sousim_pix=1280 # nombre de pixels dans la direction X
                        # pour une sous image
L=0.8   # largeur de la base de la plaque en metres

nbimage = np.arange(1,649+81,81) # numero d'images
nbimage = np.reshape(nbimage,(np.size(nbimage),1))


# Question 1
bracs = plt.imread('brachistochrone9.png')
imgplot = plt.imshow(bracs)

# Question 2
PointsL = np.array(plt.ginput(2)) #(fonction à utiliser dans l'invite de la fenêtre de commande de préférence)
#%%
Lpix = np.abs(PointsL[1,0] - PointsL[0,0]) # 923 et 61 ont ete releves avec plt.ginput(2)
taillepix=L/Lpix
                    
# Question 3
tvec =(nbimage-1)/fps # ne pas oublier de soustraire pour avoir t=0s
                                       # sur l'image 1.
#%%
# Question 4
                                       
bracs = plt.imread('brachistochrone9.png')
imgplot = plt.imshow(bracs)
coord = np.array(plt.ginput(9)) #permet de recuperer les coordonnees de la balle blanche.
#%%
xb=np.zeros(shape=(len(coord),1)) 
#xb = [68,91,144,1495,1588,1710,3132,3295,3484]

for i in range(len(coord)):
    xb[i] = coord[i,0]

xbr = xb.copy() #Soustraire la largeur de la sous image pour les sous images des col 2 et 3

xbr[3:6] = xbr[3:6] - larg_sousim_pix
xbr[6:9] = xbr[6:9] - 2*larg_sousim_pix

xbr = (xbr - xbr[0])*taillepix # On soustrait la premiere valeur pour translater le repere. On convertit les pixels en metres.

# Question 5

plt.plot(tvec, xbr, '-b', label='Experience', marker = 'o')
plt.legend(fontsize=16)
plt.show()


**Nous allons maintenant comparer ce graphique expérimental avec le modèle théorique**


6) A l'aide de l'image *brachistochroneSolo.png*, trouvez l'angle en radians que fait le plan incliné avec l'horizontale.

7) On choisit une première valeur test de $K=K_{test}=0.45$.

Superposez la courbe expérimentale avec la formule théorique (avec $K_{test}$). Ajouter une légende. Etes-vous satisfait de ce résultat?

8) Pour quantifier l'erreur  entre les courbes expérimentale et théorique pour $K_{test}$, on la calcule  au sens des moindres carrés :

$$ E= \sqrt{ \sum_{i=1}^{9} (x^{exp}_i - x^{test}_i)^2 }$$  

Que vaut $E$ pour $K_{test}$?

9) On veut maintenant voir quelle valeur de $K$ permet d'approcher au mieux la courbe expérimentale au sens des moindres carrés. 

Faire varier $K$ entre $0.25$ et $0.50$, avec un pas de $0.005$. Tracer l'erreur $E$ en fonction de $K$, et
identifier la valeur optimale $K_{opt}$ qui permet de minimiser l'erreur au sens des moindres carrés.

10) Superposer la courbe expérimentale avec la formule théorique obtenue avec $K_{opt}$.  Ajouter une légende.
La théorie donne  $K_{theo}=5/14$. Quel est l'écart entre $K_{opt}$ et $K_{theo}$?

  Pensez-vous que cet écart entre dans les incertitudes de mesure?


In [28]:

# Question 6
#En faisant le rapport des distances en pixel lues avec ginput on trouve l'angle

bracs = plt.imread('brachistochroneSolo.png')
imgplot = plt.imshow(bracs)
PointsH = np.array(plt.ginput(2))
#%%
Hpix = np.abs(PointsH[1,1] - PointsH[0,1]) # 710 et 46 ont ete releves avec plt.ginput(2)
alphatheo= np.arctan(Hpix/Lpix);

# Question 7  
# loi theorique avec Ktest=0.5
Ktest=0.45
xtest=np.cos(alphatheo)*np.power(tvec,2)*g*np.sin(alphatheo)*Ktest;
plt.plot(tvec, xtest, '-r', label="Theorie Ktest= "+ str(Ktest))
plt.xlabel('t (s)')
plt.ylabel('x (m)')
plt.title('Comparaison theorie/experience')
plt.legend(fontsize=16)
plt.show()

#%%
#la courbe semble assez proche mais on doit pouvoir faire mieux
# Question 8
# erreur moindres carrés
E=np.sqrt(np.sum(np.subtract(np.power(xtest,xbr),2)))
print('Voici l''erreur pour K=5/14 : ' + str(E)) # resultat 0.2972

# Question 9
# Minimisation de l''erreur
K=np.arange(0.25,0.5+0.005,0.005)
Ebis = np.zeros(shape=(len(K),1))

for i in range(len(K)):
    xtheo=np.cos(alphatheo)*np.power(tvec,2)*g*np.sin(alphatheo)*K[i];
    xtheo = np.reshape(xtheo,(np.size(xtheo),1))
    Ebis[i]=(np.sqrt(np.sum(np.power(np.subtract(xtheo,xbr),2))))

plt.plot(K, Ebis, '-b', label='Erreur moindre carrés theo/expe', marker = 'o')
plt.xlabel('K')
plt.ylabel('E')
plt.legend(fontsize=16)
plt.show()

#%%
Kopt=K[np.argmin(Ebis)]
Eopt=min(Ebis);
print('La valeur de Kopt est '+ str(Kopt)) # resultat:0.36
print('Voici lerreur pour K=Kopt '+ str(Eopt)) # resultat:0.0463

# Question 10 Tracé courbe pour Kopt avec les autres courbes
xtheoopt=np.cos(alphatheo)*np.power(tvec,2)*g*np.sin(alphatheo)*Kopt;
xtheoopt = np.reshape(xtheoopt,(np.size(xtheoopt),1))

plt.plot(tvec, xtheoopt, '-g', label="Theorie Kopt= "+ str(round(Kopt,2)))
plt.legend(fontsize=16)
plt.show()
print('L''écart |Kopt - Ktheo| est ' + str(np.abs(Kopt-5/14))) 

# réponse écart 0.0029 : c'est très faible
# L'erreur moindre carrés varie de 0.02
# si on trace les courbes avec Ktheo et Kopt elles sont très proches

[0.         0.0158468  0.06338719 0.14262118 0.25354876 0.39616993
 0.5704847  0.77649307 1.01419503]
[0.0, 0.02134570765661253, 0.07053364269141531, 0.13642691415313224, 0.22273781902552203, 0.3359628770301624, 0.4677494199535963, 0.6190255220417633, 0.794431554524362]
Voici lerreur pour K=5/14 : 0.2972211856351354
La valeur de Kopt est 0.25
Voici lerreur pour K=Kopt [3.05148888]
Lécart |Kopt - Ktheo| est 0.10714285714285715


In [27]:
print(np.subtract(xtest,xbr)**2)

[0.00000000e+00 3.02380149e-05 5.10717966e-05 3.83688779e-05
 9.49313902e-04 3.62488958e-03 1.05545385e-02 2.47960282e-02
 4.82959844e-02]


## I.2) Calcul de la longueur de chaque trajectoire. Estimation de la vitesse moyenne de chaque boule
 

11) Sur l'image *brachistochroneSolo.png* à l'aide de la fonction *ginput* récupérez les coordonnées des tracés blanc, rouge et jaune. Superposez-les sur l'image 

12) En plaçant le centre $O$ d'un système cartésien $(0,\vec{x},\vec{y})$ au point de départ des trajectoires, effectuez le changement de repère nécessaire et tracer dans une nouvelle figure  les courbes $y(x)$ représentant chaque trajectoire avec $x$ et $y$ en mètres. 

13) A partir de vos relevés, calculez une valeur approchée de la longueur en mètre de chaque tracé.

14) Le numéro de l'image de démarrage ($t=0s$) est 1. Les boules blanche, rouge et jaune arrivent respectivement aux numéros d'image 649, 521, 577. Calculez la vitesse moyenne de chaque boule. Concluez.

In [ ]:

# Comparaison des trajectoires
# from scipy import io

# Question 11
# Prises de mesure sur image à l'aide de l'outil ginput à utiliser dans l'invite de commande, les fichiers .mat contiennent les trajectoires à relever

bracsolo = plt.imread('brachistochronesolo.png')
imgplot = plt.imshow(bracsolo)
trajectoireblanche = np.array(plt.ginput(23))
#%%

bracsolo = plt.imread('brachistochronesolo.png')
imgplot = plt.imshow(bracsolo)
trajectoirerouge = np.array(plt.ginput(23))
#%%

bracsolo = plt.imread('brachistochronesolo.png')
imgplot = plt.imshow(bracsolo)
trajectoirejaune = np.array(plt.ginput(23))
#%%

x1 = np.zeros(shape=(len(trajectoireblanche),1))
y1 = np.zeros(shape=(len(trajectoireblanche),1))

x2 = np.zeros(shape=(len(trajectoirejaune),1))
y2 = np.zeros(shape=(len(trajectoirejaune),1))

x3 = np.zeros(shape=(len(trajectoirerouge),1))
y3 = np.zeros(shape=(len(trajectoirerouge),1))


for i in range(len(trajectoireblanche)):
    x1[i] = trajectoireblanche[i,0]
    y1[i] = trajectoireblanche[i,1]
    

for i in range(len(trajectoirerouge)):
    x2[i] = trajectoirerouge[i,0]
    y2[i] = trajectoirerouge[i,1]
    

for i in range(len(trajectoirejaune)):
    x3[i] = trajectoirejaune[i,0]
    y3[i] = trajectoirejaune[i,1]


#trajectoirejaune = io.loadmat("trajectoirejaune.Mat")
#trajectoirerouge = io.loadmat("trajectoirerouge.Mat")
#trajectoireblanche = io.loadmat("trajectoireblanche.Mat")

# On superpose les trajectoires lues sur l'image d'origine
plt.plot(x1, y1, '-b')
plt.plot(x2, y2, '-r')
plt.plot(x3, y3, '-y')
plt.show()

#avec les trajectoires des fichiers .mat
#plt.plot(trajectoireblanche['xpix1'], trajectoireblanche['ypix1'], '-w')
#plt.plot(trajectoirerouge['xpix2'], trajectoirerouge['ypix2'], '-r')
#plt.plot(trajectoirejaune['xpix3'], trajectoirejaune['ypix3'], '-y')


#%%
# Question 12
# changement de repère des trajectoires

for i in range(len(x1)):
    x1[i] = x1[i] - x1[0]
    y1[i] = -(y1[i] - y1[0])
    
for i in range(len(x1)):
    x2[i] = x2[i] - x2[0]
    y2[i] = -(y2[i] - y2[0])
    

for i in range(len(x1)):
    x3[i] = x3[i] - x3[0]
    y3[i] = -(y3[i] - y3[0])

#avec les trajectoires des fichiers .mat
#x1 = [(x - trajectoireblanche['xpix1'][0])*taillepix for x in trajectoireblanche['xpix1']]
#y1 = [-(y - trajectoireblanche['ypix1'][0])*taillepix for y in trajectoireblanche['ypix1']]

#x2 = [(x - trajectoirerouge['xpix2'][0])*taillepix for x in trajectoirerouge['xpix2']]
#y2 = [-(y - trajectoirerouge['ypix2'][0])*taillepix for y in trajectoirerouge['ypix2']]

#x3 = [(x - trajectoirejaune['xpix3'][0])*taillepix for x in trajectoirejaune['xpix3']]
#y3 = [-(y - trajectoirejaune['ypix3'][0])*taillepix for y in trajectoirejaune['ypix3']]


plt.plot(x1,y1,'-b', label="Trajectoir blanche")
plt.plot(x2,y2,'-r', label="Trajectoir rouge")
plt.plot(x3,y3,'-y', label="Trajectoir jaune")
plt.legend(fontsize=10)
plt.xlabel('x')
plt.ylabel('y')
plt.title('Trajectoire dans le repere (0,x,y)')
plt.show()

#%%
# Question 13
#Calcul des longueurs des trajectoires
long1=0
long2=0
long3=0

for i in range(len(x1)-1):
    dx=x1[i+1]-x1[i]
    dy=y1[i+1]-y1[i]
    long1=long1+np.sqrt(dx**2+dy**2);
    
for i in range(len(x2)-1):
    dx=x2[i+1]-x2[i]
    dy=y2[i+1]-y2[i]
    long2=long2+np.sqrt(dx**2+dy**2);
    
for i in range(len(x3)-1):
    dx=x3[i+1]-x3[i]
    dy=y3[i+1]-y3[i]
    long3=long3+np.sqrt(dx**2+dy**2);

print('Les longueurs valent respectivement : \n')
print(' trajectoire blanche = '+ str(long1) + '\n')
print(' trajectoire rouge= '+ str(long2) + '\n')
print(' trajectoire jaune = '+ str(long3) + '\n')

# Question 14
# calcul des vitesses moyennes.
longueur=np.array([long1, long2, long3]);
t=np.array([649, 521, 577])
t=(t-1)/fps  # on soustrait 1 au num d'image.
vit_moy = longueur / t 

print('Les vitesses moyennes valent respectivement : \n')
print(' trajectoire blanche = '+ str(vit_moy[0]) + '\n')
print(' trajectoire rouge= '+ str(vit_moy[1]) + '\n')
print(' trajectoire jaune = '+ str(vit_moy[2]) + '\n')

# Partie II. Opérations avec des logiques


1) Etant donné $x=\begin{bmatrix} 3&15&9&-12&-1&0&12&9&6&1\end{bmatrix} $, écrire la commande ($\textbf{une seule instruction !}$) qui permet de réaliser les fonctionnalités suivantes: (dans votre script, si le vecteur x est modifié par la commande, il faut le réinitialiser à sa valeur de départ avant de faire la commande suivante)

*  Mise à zéro des valeurs de x positives ou nulles, les autres valeurs sont conservées ;
*  Mise à la valeur 3 des valeurs de x qui sont des multiples de 3, les autres valeurs sont conservées ;
*  Multiplication des valeurs paires par 5, les autres valeurs sont conservées ;
*  Extraction des valeurs de x qui sont supérieures ou égales à 10 pour les placer dans un vecteur y ;
*  Mise à la valeur moyenne de toutes les valeurs de x qui sont strictement inférieures à la valeur moyenne des éléments de x, les autres valeurs sont conservées ; (Bien penser à convertir le tableau en float pour faire cette opération) 
*  Remplacement de la valeur des éléments de x strictement supérieures à la valeur moyenne des éléments de x par la différence entre cette valeur et la moyenne, les autres valeurs sont conservées.

Le fonctions de `numpy` np.mod (ou %) et np.mean peuvent être utiles.

In [1]:
import numpy as np

x = np.array([3.0,15,9,-12,-1,0,12,9,6,1])
print(x)
# x doesn't change, we work with an auxiliar array a=x
a = x.copy()
a[a>=0]=0
print(a)

a = x.copy()
a[a%3==0]=3
print(a)


a=x.copy()
a[a%2==0]= 5*a[a%2==0]
print(a)


a=x.copy()
y= a[a>=10]
print(y)


#copy x and change type
#a=x.astype('float')
a = x.copy()
a[a<np.mean(a)]= np.mean(a)
print(a)


a=x.astype('float')
a[a>np.mean(a)]= a[a>np.mean(a)]-np.mean(a)
print(a)

[  3.  15.   9. -12.  -1.   0.  12.   9.   6.   1.]
[  0.   0.   0. -12.  -1.   0.   0.   0.   0.   0.]
[ 3.  3.  3.  3. -1.  3.  3.  3.  3.  1.]
[  3.  15.   9. -60.  -1.   0.  60.   9.  30.   1.]
[ 15.  12.]
[  4.2  15.    9.    4.2   4.2   4.2  12.    9.    6.    4.2]
[  3.   10.8   4.8 -12.   -1.    0.    7.8   4.8   1.8   1. ]
